#! /bin/sh
### BEGIN INIT INFO
# Provides: phabricator-notification
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: PhabricatorNotification
# Description: Manage Phabricator Aphlict notification server
#
### END INIT INFO

## Configuration
NOTIFICATION_USER=phd
PHABRICATOR_HOME=/var/www/phab/phabricator

case "$1" in
 start)
   sudo -u $NOTIFICATION_USER "$PHABRICATOR_HOME/bin/aphlict" restart
   ;;
 stop)
   sudo -u $NOTIFICATION_USER "$PHABRICATOR_HOME/bin/aphlict" stop
   ;;
 restart)
   sudo -u $NOTIFICATION_USER "$PHABRICATOR_HOME/bin/aphlict" restart
   ;;
 status)
   sudo -u $NOTIFICATION_USER "$PHABRICATOR_HOME/bin/aphlict" status
   ;;
 *)
   echo "Usage: service phabricator-notification {start|stop|restart|status}" >&2
   exit 3
   ;;
esac
