#! /bin/sh
### BEGIN INIT INFO
# Provides: phabricator-daemon
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: PhabricatorDaemon
# Description: Manage Phabricator PHD daemon
#
### END INIT INFO

## Configuration
DAEMON_USER=phd
PHABRICATOR_HOME=/var/www/phab/phabricator

case "$1" in
 start)
   sudo -u $DAEMON_USER "$PHABRICATOR_HOME/bin/phd" start
   ;;
 stop)
   sudo -u $DAEMON_USER "$PHABRICATOR_HOME/bin/phd" stop
   ;;
 restart)
   sudo -u $DAEMON_USER "$PHABRICATOR_HOME/bin/phd" restart
   ;;
 status)
   sudo -u $DAEMON_USER "$PHABRICATOR_HOME/bin/phd" status
   ;;
 *)
   echo "Usage: service phabricator-daemon {start|stop|restart|status}" >&2
   exit 3
   ;;
esac
